# Generated by Django 2.2.5 on 2019-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField()),
                ('handle', models.CharField(max_length=16)),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(max_length=512)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
